version: "3.7"
services:
  postgres:
    container_name: 'to-do-postgres'
    image: 'postgres:12.19'
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB= ${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    container_name: 'to-do-redis'
    image: 'redis:5.0.5'
    ports:
      - '6379:6379'

volumes:
  pgdata: